Vagrant.configure("2") do |config|
  # * Provider-specific configuration
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048 # * 2GB of memory
    libvirt.cpus = 2      # * 2 cores
    libvirt.qemu_use_session = false
    libvirt.driver = "kvm"
  end

  # * Box distribution
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"

  # * Provisioning all VMs
  config.vm.provision "upgrade and firewall",
    type: "shell",
    inline: <<-SHELL
      apt-get update

      ufw allow 6443/tcp                 # Api Server
      ufw allow from 10.42.0.0/16 to any # Pods
      ufw allow from 10.43.0.0/16 to any # Services
  SHELL

  # * Base box configuration
  config.vm.define "noalexanS" do |noalexanS|
    noalexanS.vm.hostname = "noalexanS"

    # * Network configuration
    noalexanS.vm.network :private_network, ip: "192.168.56.110",
      libvirt__host_ip: "192.168.56.1",
      libvirt__network_name: "vagrant-libvirt-p2",
      libvirt__dhcp_enabled: false

    # * K3s installation in controller mode
    noalexanS.vm.provision "k3s - controller mode",
      type: "shell",
      inline: <<-SHELL
        curl -sfL https://get.k3s.io | sh -
        chown -v vagrant:vagrant /etc/rancher/k3s/k3s.yaml
    SHELL

    noalexanS.vm.provision "file", source: "./confs", destination: "/home/vagrant/confs"

    noalexanS.vm.provision "deploy app1",
      type: "shell",
      inline: <<-SHELL
        kubectl create configmap nginx-app1-html --from-file=/home/vagrant/confs/app1/index-app1.html
        kubectl apply -f /home/vagrant/confs/app1/deployment-app1.yaml
        kubectl apply -f /home/vagrant/confs/app1/service-app1.yaml
    SHELL

    noalexanS.vm.provision "deploy app2",
      type: "shell",
      inline: <<-SHELL
        kubectl create configmap nginx-app2-html --from-file=/home/vagrant/confs/app2/index-app2.html
        kubectl apply -f /home/vagrant/confs/app2/deployment-app2.yaml
        kubectl apply -f /home/vagrant/confs/app2/service-app2.yaml
    SHELL

    noalexanS.vm.provision "deploy app3",
      type: "shell",
      inline: <<-SHELL
        kubectl create configmap nginx-app3-html --from-file=/home/vagrant/confs/app3/index-app3.html
        kubectl apply -f /home/vagrant/confs/app3/deployment-app3.yaml
        kubectl apply -f /home/vagrant/confs/app3/service-app3.yaml
    SHELL

    noalexanS.vm.provision "deploy ingress",
      type: "shell",
      inline: <<-SHELL
        kubectl apply -f /home/vagrant/confs/ingress.yaml
    SHELL
  end
end
