
Vagrant.configure("2") do |config|

  # * Provider-specific configuration
  config.vm.provider :libvirt do |libvirt|
    # * 6GB of memory
    libvirt.memory = 6144
    # * 4 cores
    libvirt.cpus = 4
    libvirt.qemu_use_session = false
    libvirt.driver = "kvm"
  end

  config.vm.box = "generic/fedora28"
  config.vm.box_version = "4.3.12"

	# * Provisioning all VMs
  config.vm.provision "upgrade", type: "shell", privileged: true, before: :all, inline: <<-SHELL
    echo "[upgrade provision] Upgrading system packages..."
    sudo dnf upgrade -y --refresh
  SHELL

  # * Base box configuration
  config.vm.define "noalexanS" do |noalexanS|
    noalexanS.vm.hostname = "noalexanS"
    noalexanS.vm.network :private_network,ip: "192.168.56.110",
      libvirt__host_ip: "192.168.56.1",
      libvirt__network_name: "vagrant-libvirt",
      libvirt__dhcp_enabled: false
  end

  config.vm.define "mayoubSW" do |mayoubSW|
    mayoubSW.vm.hostname = "mayoubSW"
    mayoubSW.vm.network :private_network,ip: "192.168.56.111",
      libvirt__host_ip: "192.168.56.1",
      libvirt__network_name: "vagrant-libvirt",
      libvirt__dhcp_enabled: false
  end

end
