Vagrant.configure("2") do |config|

  # * Provider-specific configuration
  config.vm.provider :libvirt do |libvirt|
    # * 8GB of memory
    libvirt.memory = 8192
    # * 6 cores
    libvirt.cpus = 6
    libvirt.qemu_use_session = false
    libvirt.driver = "kvm"
  end

  # * Box distribution
  config.vm.box = "generic/ubuntu1804"
  config.vm.box_version = "4.3.12"

	# * Provisioning all VMs
  config.vm.provision "upgrade",
    type: "shell",
    privileged: true,
    before: :all,

    inline: <<-SHELL
    echo "[upgrade] Upgrading system packages..."
    sudo apt-get --fix-broken install -y
    sudo apt-get update
    sudo apt-get upgrade -y
  SHELL

  # * Base box configuration
  config.vm.define "noalexanS" do |noalexanS|
    noalexanS.vm.hostname = "noalexanS"

    # * Network configuration
    noalexanS.vm.network :private_network, ip: "192.168.56.110",
      libvirt__host_ip: "192.168.56.1",
      libvirt__network_name: "vagrant-libvirt-p3",
      libvirt__dhcp_enabled: false
  end

end
